CREATE TABLE IF NOT EXISTS account (
    id SERIAL PRIMARY KEY,
    balance_usd DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS holding (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    amount DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS transaction (
    id SERIAL PRIMARY KEY,
    action VARCHAR(10) NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    amount_crypto DOUBLE PRECISION NOT NULL,
    price_per_unit DOUBLE PRECISION NOT NULL,
    total_usd DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
